plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/runner/work/effect-libs/effect-libs/packages/effect-libs/netlify-site"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]