/**
 * Internal module that represents the result of merging the entries of a
 * `nonPrimitiveParametersArray` that apply to a given non-primitive value. Carries every field of
 * `PPNonPrimitiveParameters` except `id` and `isApplicableTo`, all mandatory and populated from the
 * matching entries (lower-index wins) with any remaining gaps filled by `utilInspectLikeRecord`.
 */

import { pipe } from 'effect';
import * as Array from 'effect/Array';
import * as Option from 'effect/Option';
import * as Struct from 'effect/Struct';

import { MData } from '@parischap/effect-lib';
import * as MStruct from '@parischap/effect-lib/MStruct';
import type * as MTypes from '@parischap/effect-lib/MTypes';

import type * as PPNonPrimitiveParameters from '../../Parameters/NonPrimitiveParameters.js';
import type * as PPValueOrder from '../../Parameters/ValueOrder.js';
import type * as PPResolvedNonPrimitiveParameters from './ResolvedNonPrimitiveParameters.js';

import * as PPByPasser from '../../Parameters/ByPasser.js';
import * as PPNonPrimitiveFormatter from '../../Parameters/NonPrimitiveFormatter.js';
import * as PPPropertyFilter from '../../Parameters/PropertyFilter.js';
import * as PPPropertyFormatter from '../../Parameters/PropertyFormatter.js';
import * as PPPropertyNumberDisplayOption from '../../Parameters/PropertyNumberDisplayOption.js';

/**
 * Module tag
 *
 * @category Module markers
 */
export const moduleTag = '@parischap/internal/Parameters/ResolvedNonPrimitiveParameters';
const _TypeId: unique symbol = Symbol.for(moduleTag) as _TypeId;
type _TypeId = typeof _TypeId;

/**
 * Type that represents a
 *
 * @category Models
 */
export class Type extends MData.Class {
  readonly showName: boolean;
  readonly propertyNumberDisplayOption: PPPropertyNumberDisplayOption.Type;
  readonly byPasser: PPByPasser.Type;
  readonly maxPrototypeDepth: number;
  readonly propertyFilter: PPPropertyFilter.Type;
  readonly propertySortOrder: Option.Option<PPValueOrder.Type>;
  readonly dedupeProperties: boolean;
  readonly maxPropertyNumber: number;
  readonly propertyFormatter: PPPropertyFormatter.Type;
  readonly nonPrimitiveFormatter: PPNonPrimitiveFormatter.Type;
  readonly hideAutoGeneratedKeys: boolean;
  readonly extractIterableElements: boolean;

  /** Returns the `id` of `this` */
  [MData.idSymbol](): string | (() => string) {
    return moduleTag;
  }

  /** Class constructor */
  public constructor({
    showName,
    propertyNumberDisplayOption,
    byPasser,
    maxPrototypeDepth,
    propertyFilter,
    propertySortOrder,
    dedupeProperties,
    maxPropertyNumber,
    propertyFormatter,
    nonPrimitiveFormatter,
    hideAutoGeneratedKeys,
    extractIterableElements,
  }: MTypes.Data<Type>) {
    super();
    this.showName = showName;
    this.propertyNumberDisplayOption = propertyNumberDisplayOption;
    this.byPasser = byPasser;
    this.maxPrototypeDepth = maxPrototypeDepth;
    this.propertyFilter = propertyFilter;
    this.propertySortOrder = propertySortOrder;
    this.dedupeProperties = dedupeProperties;
    this.maxPropertyNumber = maxPropertyNumber;
    this.propertyFormatter = propertyFormatter;
    this.nonPrimitiveFormatter = nonPrimitiveFormatter;
    this.hideAutoGeneratedKeys = hideAutoGeneratedKeys;
    this.extractIterableElements = extractIterableElements;
  }

  /** Returns the TypeMarker of the class */
  protected get [_TypeId](): _TypeId {
    return _TypeId;
  }
}

/**
 * Constructor of a PPResolvedNonPrimitiveParameters
 *
 * @category Constructors
 */
export const make = (params: MTypes.Data<Type>): Type => new Type(params);

/**
 * Bound on the number of cached merge results. Unique applicable subsets for a single
 * `PPParameters` are at most 2^N (N = entries in the array), which is small in practice; the cap
 * exists only to keep memory bounded if the `PPParameters` is reconfigured frequently.
 */
const CACHE_CAPACITY = 20;

/** Module-level cache of merge results, keyed by the `+`-joined ids of the applicable entries */
const cache = new Map<string, PPResolvedNonPrimitiveParameters.Type>();

/**
 * Filters `self` down to the entries applicable to `nonPrimitive`, merges them into a
 * `PPResolvedNonPrimitiveParameters` (lower-index entries overriding higher-index ones, defaults
 * filling any remaining gaps), and caches the result by the `+`-joined ids of the applicable
 * entries.
 *
 * @category Constructors
 */
export const fromApplicableNonPrimitiveParameters = ({
  nonPrimitive,
  nonPrimitiveParametersArray,
}: {
  nonPrimitive: MTypes.NonPrimitive;
  nonPrimitiveParametersArray: MTypes.OverOne<PPNonPrimitiveParameters.Type>;
}): Type => {
  const applicable = pipe(
    nonPrimitiveParametersArray,
    Array.filter((entry) => entry.isApplicableTo(nonPrimitive)),
  );
  const key = pipe(applicable, Array.map(Struct.get('id')), Array.join('+'));
  const cached = cache.get(key);
  if (cached !== undefined) return cached;

  const merged = pipe(
    applicable,
    Array.reduceRight(utilInspectLikeRecord, (acc, item) => pipe(acc, MStruct.append(item), make)),
  );

  if (cache.size >= CACHE_CAPACITY) {
    const oldestKey = cache.keys().next().value;
    if (oldestKey !== undefined) cache.delete(oldestKey);
  }
  cache.set(key, merged);
  return merged;
};

/**
 * Default value for each optional field of `Type`. Used by
 * `fromApplicableNonPrimitiveParameters` as the seed of the reduction so that the merged result is
 * fully populated even when no entry sets a given field. Mimics Node.js's `util.inspect` for plain
 * records.
 *
 * @category Instances
 */
export const utilInspectLikeRecord: Type = make({
  showName: false,
  propertyNumberDisplayOption: PPPropertyNumberDisplayOption.Type.None,
  propertySortOrder: Option.none<PPValueOrder.Type>(),
  dedupeProperties: false,
  byPasser: PPByPasser.dateAndRegExp,
  maxPrototypeDepth: 1,
  maxPropertyNumber: +Infinity,
  propertyFilter: PPPropertyFilter.removeNonEnumerables,
  nonPrimitiveFormatter: PPNonPrimitiveFormatter.utilInspectLikeRecord,
  propertyFormatter: PPPropertyFormatter.utilInspectLikeArrayAndRecord,
  hideAutoGeneratedKeys: true,
  extractIterableElements: false,
});
