// ************** This file is automatically generated. Any modifications will be lost ************************

import {plainEslintConfig} from '@parischap/configs/EslintConfig';
export default plainEslintConfig({tsconfigRootDir:import.meta.dirname})