/** This module implements the possible eight-bit color codes */
import * as MMatch from '@parischap/effect-lib/MMatch'
import * as MTypes from '@parischap/effect-lib/MTypes'
import {flow} from 'effect'
import * as Function from 'effect/Function'

/**
 * Type of an ASEightBitColorCode
 *
 * @category Models
 */
export enum Type {
  Black = 0,
  Maroon = 1,
  Green = 2,
  Olive = 3,
  Navy = 4,
  Purple_1 = 5,
  Teal = 6,
  Silver = 7,
  Grey = 8,
  Red = 9,
  Lime = 10,
  Yellow = 11,
  Blue = 12,
  Fuchsia = 13,
  Aqua = 14,
  White = 15,
  Grey0 = 16,
  NavyBlue = 17,
  DarkBlue = 18,
  Blue3_1 = 19,
  Blue3_2 = 20,
  Blue1 = 21,
  DarkGreen = 22,
  DeepSkyBlue4_1 = 23,
  DeepSkyBlue4_2 = 24,
  DeepSkyBlue4_3 = 25,
  DodgerBlue3 = 26,
  DodgerBlue2 = 27,
  Green4 = 28,
  SpringGreen4 = 29,
  Turquoise4 = 30,
  DeepSkyBlue3_1 = 31,
  DeepSkyBlue3_2 = 32,
  DodgerBlue1 = 33,
  Green3_1 = 34,
  SpringGreen3_1 = 35,
  DarkCyan = 36,
  LightSeaGreen = 37,
  DeepSkyBlue2 = 38,
  DeepSkyBlue1 = 39,
  Green3_2 = 40,
  SpringGreen3_2 = 41,
  SpringGreen2_1 = 42,
  Cyan3 = 43,
  DarkTurquoise = 44,
  Turquoise2 = 45,
  Green1 = 46,
  SpringGreen2_2 = 47,
  SpringGreen1 = 48,
  MediumSpringGreen = 49,
  Cyan2 = 50,
  Cyan1 = 51,
  DarkRed_1 = 52,
  DeepPink4_1 = 53,
  Purple4_1 = 54,
  Purple4_2 = 55,
  Purple3 = 56,
  BlueViolet = 57,
  Orange4_1 = 58,
  Grey37 = 59,
  MediumPurple4 = 60,
  SlateBlue3_1 = 61,
  SlateBlue3_2 = 62,
  RoyalBlue1 = 63,
  Chartreuse4 = 64,
  DarkSeaGreen4_1 = 65,
  PaleTurquoise4 = 66,
  SteelBlue = 67,
  SteelBlue3 = 68,
  CornflowerBlue = 69,
  Chartreuse3_1 = 70,
  DarkSeaGreen4_2 = 71,
  CadetBlue_1 = 72,
  CadetBlue_2 = 73,
  SkyBlue3 = 74,
  SteelBlue1_1 = 75,
  Chartreuse3_2 = 76,
  PaleGreen3_1 = 77,
  SeaGreen3 = 78,
  Aquamarine3 = 79,
  MediumTurquoise = 80,
  SteelBlue1_2 = 81,
  Chartreuse2_1 = 82,
  SeaGreen2 = 83,
  SeaGreen1_1 = 84,
  SeaGreen1_2 = 85,
  Aquamarine1_1 = 86,
  DarkSlateGray2 = 87,
  DarkRed_2 = 88,
  DeepPink4_2 = 89,
  DarkMagenta_1 = 90,
  DarkMagenta_2 = 91,
  DarkViolet_1 = 92,
  Purple_2 = 93,
  Orange4_2 = 94,
  LightPink4 = 95,
  Plum4 = 96,
  MediumPurple3_1 = 97,
  MediumPurple3_2 = 98,
  SlateBlue1 = 99,
  Yellow4_1 = 100,
  Wheat4 = 101,
  Grey53 = 102,
  LightSlateGrey = 103,
  MediumPurple = 104,
  LightSlateBlue = 105,
  Yellow4_2 = 106,
  DarkOliveGreen3_1 = 107,
  DarkSeaGreen = 108,
  LightSkyBlue3_1 = 109,
  LightSkyBlue3_2 = 110,
  SkyBlue2 = 111,
  Chartreuse2_2 = 112,
  DarkOliveGreen3_2 = 113,
  PaleGreen3_2 = 114,
  DarkSeaGreen3_1 = 115,
  DarkSlateGray3 = 116,
  SkyBlue1 = 117,
  Chartreuse1 = 118,
  LightGreen_1 = 119,
  LightGreen_2 = 120,
  PaleGreen1_1 = 121,
  Aquamarine1_2 = 122,
  DarkSlateGray1 = 123,
  Red3_1 = 124,
  DeepPink4_3 = 125,
  MediumVioletRed = 126,
  Magenta3_1 = 127,
  DarkViolet_2 = 128,
  Purple_3 = 129,
  DarkOrange3_1 = 130,
  IndianRed_1 = 131,
  HotPink3_1 = 132,
  MediumOrchid3 = 133,
  MediumOrchid = 134,
  MediumPurple2_1 = 135,
  DarkGoldenRod = 136,
  LightSalmon3_1 = 137,
  RosyBrown = 138,
  Grey63 = 139,
  MediumPurple2_2 = 140,
  MediumPurple1 = 141,
  Gold3_1 = 142,
  DarkKhaki = 143,
  NavajoWhite3 = 144,
  Grey69 = 145,
  LightSteelBlue3 = 146,
  LightSteelBlue = 147,
  Yellow3_1 = 148,
  DarkOliveGreen3_3 = 149,
  DarkSeaGreen3_2 = 150,
  DarkSeaGreen2_1 = 151,
  LightCyan3 = 152,
  LightSkyBlue1 = 153,
  GreenYellow = 154,
  DarkOliveGreen2 = 155,
  PaleGreen1_2 = 156,
  DarkSeaGreen2_2 = 157,
  DarkSeaGreen1_1 = 158,
  PaleTurquoise1 = 159,
  Red3_2 = 160,
  DeepPink3_1 = 161,
  DeepPink3_2 = 162,
  Magenta3_2 = 163,
  Magenta3_3 = 164,
  Magenta2_1 = 165,
  DarkOrange3_2 = 166,
  IndianRed_2 = 167,
  HotPink3_2 = 168,
  HotPink2 = 169,
  Orchid = 170,
  MediumOrchid1_1 = 171,
  Orange3 = 172,
  LightSalmon3_2 = 173,
  LightPink3 = 174,
  Pink3 = 175,
  Plum3 = 176,
  Violet = 177,
  Gold3_2 = 178,
  LightGoldenRod3 = 179,
  Tan = 180,
  MistyRose3 = 181,
  Thistle3 = 182,
  Plum2 = 183,
  Yellow3_2 = 184,
  Khaki3 = 185,
  LightGoldenRod2_1 = 186,
  LightYellow3 = 187,
  Grey84 = 188,
  LightSteelBlue1 = 189,
  Yellow2 = 190,
  DarkOliveGreen1_1 = 191,
  DarkOliveGreen1_2 = 192,
  DarkSeaGreen1_2 = 193,
  HoneyDew2 = 194,
  LightCyan1 = 195,
  Red1 = 196,
  DeepPink2 = 197,
  DeepPink1_1 = 198,
  DeepPink1_2 = 199,
  Magenta2_2 = 200,
  Magenta1 = 201,
  OrangeRed1 = 202,
  IndianRed1_1 = 203,
  IndianRed1_2 = 204,
  HotPink_1 = 205,
  HotPink_2 = 206,
  MediumOrchid1_2 = 207,
  DarkOrange = 208,
  Salmon1 = 209,
  LightCoral = 210,
  PaleVioletRed1 = 211,
  Orchid2 = 212,
  Orchid1 = 213,
  Orange1 = 214,
  SandyBrown = 215,
  LightSalmon1 = 216,
  LightPink1 = 217,
  Pink1 = 218,
  Plum1 = 219,
  Gold1 = 220,
  LightGoldenRod2_2 = 221,
  LightGoldenRod2_3 = 222,
  NavajoWhite1 = 223,
  MistyRose1 = 224,
  Thistle1 = 225,
  Yellow1 = 226,
  LightGoldenRod1 = 227,
  Khaki1 = 228,
  Wheat1 = 229,
  Cornsilk1 = 230,
  Grey100 = 231,
  Grey3 = 232,
  Grey7 = 233,
  Grey11 = 234,
  Grey15 = 235,
  Grey19 = 236,
  Grey23 = 237,
  Grey27 = 238,
  Grey30 = 239,
  Grey35 = 240,
  Grey39 = 241,
  Grey42 = 242,
  Grey46 = 243,
  Grey50 = 244,
  Grey54 = 245,
  Grey58 = 246,
  Grey62 = 247,
  Grey66 = 248,
  Grey70 = 249,
  Grey74 = 250,
  Grey78 = 251,
  Grey82 = 252,
  Grey85 = 253,
  Grey89 = 254,
  Grey93 = 255,
}

/**
 * Converts `self` to a string
 *
 * @category Destructors
 */
export const toString: MTypes.OneArgFunction<Type, string> = flow(
  MMatch.make,
  flow(
    flow(
      flow(
        MMatch.whenIs(Type.Black, Function.constant('Black')),
        MMatch.whenIs(Type.Maroon, Function.constant('Maroon')),
        MMatch.whenIs(Type.Green, Function.constant('Green')),
        MMatch.whenIs(Type.Olive, Function.constant('Olive')),
        MMatch.whenIs(Type.Navy, Function.constant('Navy')),
        MMatch.whenIs(Type.Purple_1, Function.constant('Purple_1')),
        MMatch.whenIs(Type.Teal, Function.constant('Teal')),
        MMatch.whenIs(Type.Silver, Function.constant('Silver')),
        MMatch.whenIs(Type.Grey, Function.constant('Grey')),
      ),
      flow(
        MMatch.whenIs(Type.Red, Function.constant('Red')),
        MMatch.whenIs(Type.Lime, Function.constant('Lime')),
        MMatch.whenIs(Type.Yellow, Function.constant('Yellow')),
        MMatch.whenIs(Type.Blue, Function.constant('Blue')),
        MMatch.whenIs(Type.Fuchsia, Function.constant('Fuchsia')),
        MMatch.whenIs(Type.Aqua, Function.constant('Aqua')),
        MMatch.whenIs(Type.White, Function.constant('White')),
        MMatch.whenIs(Type.Grey0, Function.constant('Grey0')),
        MMatch.whenIs(Type.NavyBlue, Function.constant('NavyBlue')),
      ),
      flow(
        MMatch.whenIs(Type.DarkBlue, Function.constant('DarkBlue')),
        MMatch.whenIs(Type.Blue3_1, Function.constant('Blue3_1')),
        MMatch.whenIs(Type.Blue3_2, Function.constant('Blue3_2')),
        MMatch.whenIs(Type.Blue1, Function.constant('Blue1')),
        MMatch.whenIs(Type.DarkGreen, Function.constant('DarkGreen')),
        MMatch.whenIs(Type.DeepSkyBlue4_1, Function.constant('DeepSkyBlue4_1')),
        MMatch.whenIs(Type.DeepSkyBlue4_2, Function.constant('DeepSkyBlue4_2')),
        MMatch.whenIs(Type.DeepSkyBlue4_3, Function.constant('DeepSkyBlue4_3')),
        MMatch.whenIs(Type.DodgerBlue3, Function.constant('DodgerBlue3')),
      ),
      flow(
        MMatch.whenIs(Type.DodgerBlue2, Function.constant('DodgerBlue2')),
        MMatch.whenIs(Type.Green4, Function.constant('Green4')),
        MMatch.whenIs(Type.SpringGreen4, Function.constant('SpringGreen4')),
        MMatch.whenIs(Type.Turquoise4, Function.constant('Turquoise4')),
        MMatch.whenIs(Type.DeepSkyBlue3_1, Function.constant('DeepSkyBlue3_1')),
        MMatch.whenIs(Type.DeepSkyBlue3_2, Function.constant('DeepSkyBlue3_2')),
        MMatch.whenIs(Type.DodgerBlue1, Function.constant('DodgerBlue1')),
        MMatch.whenIs(Type.Green3_1, Function.constant('Green3_1')),
        MMatch.whenIs(Type.SpringGreen3_1, Function.constant('SpringGreen3_1')),
      ),
      flow(
        MMatch.whenIs(Type.DarkCyan, Function.constant('DarkCyan')),
        MMatch.whenIs(Type.LightSeaGreen, Function.constant('LightSeaGreen')),
        MMatch.whenIs(Type.DeepSkyBlue2, Function.constant('DeepSkyBlue2')),
        MMatch.whenIs(Type.DeepSkyBlue1, Function.constant('DeepSkyBlue1')),
        MMatch.whenIs(Type.Green3_2, Function.constant('Green3_2')),
        MMatch.whenIs(Type.SpringGreen3_2, Function.constant('SpringGreen3_2')),
        MMatch.whenIs(Type.SpringGreen2_1, Function.constant('SpringGreen2_1')),
        MMatch.whenIs(Type.Cyan3, Function.constant('Cyan3')),
        MMatch.whenIs(Type.DarkTurquoise, Function.constant('DarkTurquoise')),
      ),
      flow(
        MMatch.whenIs(Type.Turquoise2, Function.constant('Turquoise2')),
        MMatch.whenIs(Type.Green1, Function.constant('Green1')),
        MMatch.whenIs(Type.SpringGreen2_2, Function.constant('SpringGreen2_2')),
        MMatch.whenIs(Type.SpringGreen1, Function.constant('SpringGreen1')),
        MMatch.whenIs(Type.MediumSpringGreen, Function.constant('MediumSpringGreen')),
        MMatch.whenIs(Type.Cyan2, Function.constant('Cyan2')),
        MMatch.whenIs(Type.Cyan1, Function.constant('Cyan1')),
        MMatch.whenIs(Type.DarkRed_1, Function.constant('DarkRed_1')),
        MMatch.whenIs(Type.DeepPink4_1, Function.constant('DeepPink4_1')),
      ),
      flow(
        MMatch.whenIs(Type.Purple4_1, Function.constant('Purple4_1')),
        MMatch.whenIs(Type.Purple4_2, Function.constant('Purple4_2')),
        MMatch.whenIs(Type.Purple3, Function.constant('Purple3')),
        MMatch.whenIs(Type.BlueViolet, Function.constant('BlueViolet')),
        MMatch.whenIs(Type.Orange4_1, Function.constant('Orange4_1')),
        MMatch.whenIs(Type.Grey37, Function.constant('Grey37')),
        MMatch.whenIs(Type.MediumPurple4, Function.constant('MediumPurple4')),
        MMatch.whenIs(Type.SlateBlue3_1, Function.constant('SlateBlue3_1')),
        MMatch.whenIs(Type.SlateBlue3_2, Function.constant('SlateBlue3_2')),
      ),
      flow(
        MMatch.whenIs(Type.RoyalBlue1, Function.constant('RoyalBlue1')),
        MMatch.whenIs(Type.Chartreuse4, Function.constant('Chartreuse4')),
        MMatch.whenIs(Type.DarkSeaGreen4_1, Function.constant('DarkSeaGreen4_1')),
        MMatch.whenIs(Type.PaleTurquoise4, Function.constant('PaleTurquoise4')),
        MMatch.whenIs(Type.SteelBlue, Function.constant('SteelBlue')),
        MMatch.whenIs(Type.SteelBlue3, Function.constant('SteelBlue3')),
        MMatch.whenIs(Type.CornflowerBlue, Function.constant('CornflowerBlue')),
        MMatch.whenIs(Type.Chartreuse3_1, Function.constant('Chartreuse3_1')),
        MMatch.whenIs(Type.DarkSeaGreen4_2, Function.constant('DarkSeaGreen4_2')),
      ),
      flow(
        MMatch.whenIs(Type.CadetBlue_1, Function.constant('CadetBlue_1')),
        MMatch.whenIs(Type.CadetBlue_2, Function.constant('CadetBlue_2')),
        MMatch.whenIs(Type.SkyBlue3, Function.constant('SkyBlue3')),
        MMatch.whenIs(Type.SteelBlue1_1, Function.constant('SteelBlue1_1')),
        MMatch.whenIs(Type.Chartreuse3_2, Function.constant('Chartreuse3_2')),
        MMatch.whenIs(Type.PaleGreen3_1, Function.constant('PaleGreen3_1')),
        MMatch.whenIs(Type.SeaGreen3, Function.constant('SeaGreen3')),
        MMatch.whenIs(Type.Aquamarine3, Function.constant('Aquamarine3')),
        MMatch.whenIs(Type.MediumTurquoise, Function.constant('MediumTurquoise')),
      ),
    ),
    flow(
      flow(
        MMatch.whenIs(Type.SteelBlue1_2, Function.constant('SteelBlue1_2')),
        MMatch.whenIs(Type.Chartreuse2_1, Function.constant('Chartreuse2_1')),
        MMatch.whenIs(Type.SeaGreen2, Function.constant('SeaGreen2')),
        MMatch.whenIs(Type.SeaGreen1_1, Function.constant('SeaGreen1_1')),
        MMatch.whenIs(Type.SeaGreen1_2, Function.constant('SeaGreen1_2')),
        MMatch.whenIs(Type.Aquamarine1_1, Function.constant('Aquamarine1_1')),
        MMatch.whenIs(Type.DarkSlateGray2, Function.constant('DarkSlateGray2')),
        MMatch.whenIs(Type.DarkRed_2, Function.constant('DarkRed_2')),
        MMatch.whenIs(Type.DeepPink4_2, Function.constant('DeepPink4_2')),
      ),
      flow(
        MMatch.whenIs(Type.DarkMagenta_1, Function.constant('DarkMagenta_1')),
        MMatch.whenIs(Type.DarkMagenta_2, Function.constant('DarkMagenta_2')),
        MMatch.whenIs(Type.DarkViolet_1, Function.constant('DarkViolet_1')),
        MMatch.whenIs(Type.Purple_2, Function.constant('Purple_2')),
        MMatch.whenIs(Type.Orange4_2, Function.constant('Orange4_2')),
        MMatch.whenIs(Type.LightPink4, Function.constant('LightPink4')),
        MMatch.whenIs(Type.Plum4, Function.constant('Plum4')),
        MMatch.whenIs(Type.MediumPurple3_1, Function.constant('MediumPurple3_1')),
        MMatch.whenIs(Type.MediumPurple3_2, Function.constant('MediumPurple3_2')),
      ),
      flow(
        MMatch.whenIs(Type.SlateBlue1, Function.constant('SlateBlue1')),
        MMatch.whenIs(Type.Yellow4_1, Function.constant('Yellow4_1')),
        MMatch.whenIs(Type.Wheat4, Function.constant('Wheat4')),
        MMatch.whenIs(Type.Grey53, Function.constant('Grey53')),
        MMatch.whenIs(Type.LightSlateGrey, Function.constant('LightSlateGrey')),
        MMatch.whenIs(Type.MediumPurple, Function.constant('MediumPurple')),
        MMatch.whenIs(Type.LightSlateBlue, Function.constant('LightSlateBlue')),
        MMatch.whenIs(Type.Yellow4_2, Function.constant('Yellow4_2')),
        MMatch.whenIs(Type.DarkOliveGreen3_1, Function.constant('DarkOliveGreen3_1')),
      ),
      flow(
        MMatch.whenIs(Type.DarkSeaGreen, Function.constant('DarkSeaGreen')),
        MMatch.whenIs(Type.LightSkyBlue3_1, Function.constant('LightSkyBlue3_1')),
        MMatch.whenIs(Type.LightSkyBlue3_2, Function.constant('LightSkyBlue3_2')),
        MMatch.whenIs(Type.SkyBlue2, Function.constant('SkyBlue2')),
        MMatch.whenIs(Type.Chartreuse2_2, Function.constant('Chartreuse2_2')),
        MMatch.whenIs(Type.DarkOliveGreen3_2, Function.constant('DarkOliveGreen3_2')),
        MMatch.whenIs(Type.PaleGreen3_2, Function.constant('PaleGreen3_2')),
        MMatch.whenIs(Type.DarkSeaGreen3_1, Function.constant('DarkSeaGreen3_1')),
        MMatch.whenIs(Type.DarkSlateGray3, Function.constant('DarkSlateGray3')),
      ),
      flow(
        MMatch.whenIs(Type.SkyBlue1, Function.constant('SkyBlue1')),
        MMatch.whenIs(Type.Chartreuse1, Function.constant('Chartreuse1')),
        MMatch.whenIs(Type.LightGreen_1, Function.constant('LightGreen_1')),
        MMatch.whenIs(Type.LightGreen_2, Function.constant('LightGreen_2')),
        MMatch.whenIs(Type.PaleGreen1_1, Function.constant('PaleGreen1_1')),
        MMatch.whenIs(Type.Aquamarine1_2, Function.constant('Aquamarine1_2')),
        MMatch.whenIs(Type.DarkSlateGray1, Function.constant('DarkSlateGray1')),
        MMatch.whenIs(Type.Red3_1, Function.constant('Red3_1')),
        MMatch.whenIs(Type.DeepPink4_3, Function.constant('DeepPink4_3')),
      ),
      flow(
        MMatch.whenIs(Type.MediumVioletRed, Function.constant('MediumVioletRed')),
        MMatch.whenIs(Type.Magenta3_1, Function.constant('Magenta3_1')),
        MMatch.whenIs(Type.DarkViolet_2, Function.constant('DarkViolet_2')),
        MMatch.whenIs(Type.Purple_3, Function.constant('Purple_3')),
        MMatch.whenIs(Type.DarkOrange3_1, Function.constant('DarkOrange3_1')),
        MMatch.whenIs(Type.IndianRed_1, Function.constant('IndianRed_1')),
        MMatch.whenIs(Type.HotPink3_1, Function.constant('HotPink3_1')),
        MMatch.whenIs(Type.MediumOrchid3, Function.constant('MediumOrchid3')),
        MMatch.whenIs(Type.MediumOrchid, Function.constant('MediumOrchid')),
      ),
      flow(
        MMatch.whenIs(Type.MediumPurple2_1, Function.constant('MediumPurple2_1')),
        MMatch.whenIs(Type.DarkGoldenRod, Function.constant('DarkGoldenRod')),
        MMatch.whenIs(Type.LightSalmon3_1, Function.constant('LightSalmon3_1')),
        MMatch.whenIs(Type.RosyBrown, Function.constant('RosyBrown')),
        MMatch.whenIs(Type.Grey63, Function.constant('Grey63')),
        MMatch.whenIs(Type.MediumPurple2_2, Function.constant('MediumPurple2_2')),
        MMatch.whenIs(Type.MediumPurple1, Function.constant('MediumPurple1')),
        MMatch.whenIs(Type.Gold3_1, Function.constant('Gold3_1')),
        MMatch.whenIs(Type.DarkKhaki, Function.constant('DarkKhaki')),
      ),
      flow(
        MMatch.whenIs(Type.NavajoWhite3, Function.constant('NavajoWhite3')),
        MMatch.whenIs(Type.Grey69, Function.constant('Grey69')),
        MMatch.whenIs(Type.LightSteelBlue3, Function.constant('LightSteelBlue3')),
        MMatch.whenIs(Type.LightSteelBlue, Function.constant('LightSteelBlue')),
        MMatch.whenIs(Type.Yellow3_1, Function.constant('Yellow3_1')),
        MMatch.whenIs(Type.DarkOliveGreen3_3, Function.constant('DarkOliveGreen3_3')),
        MMatch.whenIs(Type.DarkSeaGreen3_2, Function.constant('DarkSeaGreen3_2')),
        MMatch.whenIs(Type.DarkSeaGreen2_1, Function.constant('DarkSeaGreen2_1')),
        MMatch.whenIs(Type.LightCyan3, Function.constant('LightCyan3')),
      ),
      flow(
        MMatch.whenIs(Type.LightSkyBlue1, Function.constant('LightSkyBlue1')),
        MMatch.whenIs(Type.GreenYellow, Function.constant('GreenYellow')),
        MMatch.whenIs(Type.DarkOliveGreen2, Function.constant('DarkOliveGreen2')),
        MMatch.whenIs(Type.PaleGreen1_2, Function.constant('PaleGreen1_2')),
        MMatch.whenIs(Type.DarkSeaGreen2_2, Function.constant('DarkSeaGreen2_2')),
        MMatch.whenIs(Type.DarkSeaGreen1_1, Function.constant('DarkSeaGreen1_1')),
        MMatch.whenIs(Type.PaleTurquoise1, Function.constant('PaleTurquoise1')),
        MMatch.whenIs(Type.Red3_2, Function.constant('Red3_2')),
        MMatch.whenIs(Type.DeepPink3_1, Function.constant('DeepPink3_1')),
      ),
    ),
    flow(
      flow(
        MMatch.whenIs(Type.DeepPink3_2, Function.constant('DeepPink3_2')),
        MMatch.whenIs(Type.Magenta3_2, Function.constant('Magenta3_2')),
        MMatch.whenIs(Type.Magenta3_3, Function.constant('Magenta3_3')),
        MMatch.whenIs(Type.Magenta2_1, Function.constant('Magenta2_1')),
        MMatch.whenIs(Type.DarkOrange3_2, Function.constant('DarkOrange3_2')),
        MMatch.whenIs(Type.IndianRed_2, Function.constant('IndianRed_2')),
        MMatch.whenIs(Type.HotPink3_2, Function.constant('HotPink3_2')),
        MMatch.whenIs(Type.HotPink2, Function.constant('HotPink2')),
        MMatch.whenIs(Type.Orchid, Function.constant('Orchid')),
      ),
      flow(
        MMatch.whenIs(Type.MediumOrchid1_1, Function.constant('MediumOrchid1_1')),
        MMatch.whenIs(Type.Orange3, Function.constant('Orange3')),
        MMatch.whenIs(Type.LightSalmon3_2, Function.constant('LightSalmon3_2')),
        MMatch.whenIs(Type.LightPink3, Function.constant('LightPink3')),
        MMatch.whenIs(Type.Pink3, Function.constant('Pink3')),
        MMatch.whenIs(Type.Plum3, Function.constant('Plum3')),
        MMatch.whenIs(Type.Violet, Function.constant('Violet')),
        MMatch.whenIs(Type.Gold3_2, Function.constant('Gold3_2')),
        MMatch.whenIs(Type.LightGoldenRod3, Function.constant('LightGoldenRod3')),
      ),
      flow(
        MMatch.whenIs(Type.Tan, Function.constant('Tan')),
        MMatch.whenIs(Type.MistyRose3, Function.constant('MistyRose3')),
        MMatch.whenIs(Type.Thistle3, Function.constant('Thistle3')),
        MMatch.whenIs(Type.Plum2, Function.constant('Plum2')),
        MMatch.whenIs(Type.Yellow3_2, Function.constant('Yellow3_2')),
        MMatch.whenIs(Type.Khaki3, Function.constant('Khaki3')),
        MMatch.whenIs(Type.LightGoldenRod2_1, Function.constant('LightGoldenRod2_1')),
        MMatch.whenIs(Type.LightYellow3, Function.constant('LightYellow3')),
        MMatch.whenIs(Type.Grey84, Function.constant('Grey84')),
      ),
      flow(
        MMatch.whenIs(Type.LightSteelBlue1, Function.constant('LightSteelBlue1')),
        MMatch.whenIs(Type.Yellow2, Function.constant('Yellow2')),
        MMatch.whenIs(Type.DarkOliveGreen1_1, Function.constant('DarkOliveGreen1_1')),
        MMatch.whenIs(Type.DarkOliveGreen1_2, Function.constant('DarkOliveGreen1_2')),
        MMatch.whenIs(Type.DarkSeaGreen1_2, Function.constant('DarkSeaGreen1_2')),
        MMatch.whenIs(Type.HoneyDew2, Function.constant('HoneyDew2')),
        MMatch.whenIs(Type.LightCyan1, Function.constant('LightCyan1')),
        MMatch.whenIs(Type.Red1, Function.constant('Red1')),
        MMatch.whenIs(Type.DeepPink2, Function.constant('DeepPink2')),
      ),
      flow(
        MMatch.whenIs(Type.DeepPink1_1, Function.constant('DeepPink1_1')),
        MMatch.whenIs(Type.DeepPink1_2, Function.constant('DeepPink1_2')),
        MMatch.whenIs(Type.Magenta2_2, Function.constant('Magenta2_2')),
        MMatch.whenIs(Type.Magenta1, Function.constant('Magenta1')),
        MMatch.whenIs(Type.OrangeRed1, Function.constant('OrangeRed1')),
        MMatch.whenIs(Type.IndianRed1_1, Function.constant('IndianRed1_1')),
        MMatch.whenIs(Type.IndianRed1_2, Function.constant('IndianRed1_2')),
        MMatch.whenIs(Type.HotPink_1, Function.constant('HotPink_1')),
        MMatch.whenIs(Type.HotPink_2, Function.constant('HotPink_2')),
      ),
      flow(
        MMatch.whenIs(Type.MediumOrchid1_2, Function.constant('MediumOrchid1_2')),
        MMatch.whenIs(Type.DarkOrange, Function.constant('DarkOrange')),
        MMatch.whenIs(Type.Salmon1, Function.constant('Salmon1')),
        MMatch.whenIs(Type.LightCoral, Function.constant('LightCoral')),
        MMatch.whenIs(Type.PaleVioletRed1, Function.constant('PaleVioletRed1')),
        MMatch.whenIs(Type.Orchid2, Function.constant('Orchid2')),
        MMatch.whenIs(Type.Orchid1, Function.constant('Orchid1')),
        MMatch.whenIs(Type.Orange1, Function.constant('Orange1')),
        MMatch.whenIs(Type.SandyBrown, Function.constant('SandyBrown')),
      ),
      flow(
        MMatch.whenIs(Type.LightSalmon1, Function.constant('LightSalmon1')),
        MMatch.whenIs(Type.LightPink1, Function.constant('LightPink1')),
        MMatch.whenIs(Type.Pink1, Function.constant('Pink1')),
        MMatch.whenIs(Type.Plum1, Function.constant('Plum1')),
        MMatch.whenIs(Type.Gold1, Function.constant('Gold1')),
        MMatch.whenIs(Type.LightGoldenRod2_2, Function.constant('LightGoldenRod2_2')),
        MMatch.whenIs(Type.LightGoldenRod2_3, Function.constant('LightGoldenRod2_3')),
        MMatch.whenIs(Type.NavajoWhite1, Function.constant('NavajoWhite1')),
        MMatch.whenIs(Type.MistyRose1, Function.constant('MistyRose1')),
      ),
      flow(
        MMatch.whenIs(Type.Thistle1, Function.constant('Thistle1')),
        MMatch.whenIs(Type.Yellow1, Function.constant('Yellow1')),
        MMatch.whenIs(Type.LightGoldenRod1, Function.constant('LightGoldenRod1')),
        MMatch.whenIs(Type.Khaki1, Function.constant('Khaki1')),
        MMatch.whenIs(Type.Wheat1, Function.constant('Wheat1')),
        MMatch.whenIs(Type.Cornsilk1, Function.constant('Cornsilk1')),
        MMatch.whenIs(Type.Grey100, Function.constant('Grey100')),
        MMatch.whenIs(Type.Grey3, Function.constant('Grey3')),
        MMatch.whenIs(Type.Grey7, Function.constant('Grey7')),
      ),
      flow(
        MMatch.whenIs(Type.Grey11, Function.constant('Grey11')),
        MMatch.whenIs(Type.Grey15, Function.constant('Grey15')),
        MMatch.whenIs(Type.Grey19, Function.constant('Grey19')),
        MMatch.whenIs(Type.Grey23, Function.constant('Grey23')),
        MMatch.whenIs(Type.Grey27, Function.constant('Grey27')),
        MMatch.whenIs(Type.Grey30, Function.constant('Grey30')),
        MMatch.whenIs(Type.Grey35, Function.constant('Grey35')),
        MMatch.whenIs(Type.Grey39, Function.constant('Grey39')),
        MMatch.whenIs(Type.Grey42, Function.constant('Grey42')),
      ),
    ),
    flow(
      flow(
        MMatch.whenIs(Type.Grey46, Function.constant('Grey46')),
        MMatch.whenIs(Type.Grey50, Function.constant('Grey50')),
        MMatch.whenIs(Type.Grey54, Function.constant('Grey54')),
        MMatch.whenIs(Type.Grey58, Function.constant('Grey58')),
        MMatch.whenIs(Type.Grey62, Function.constant('Grey62')),
        MMatch.whenIs(Type.Grey66, Function.constant('Grey66')),
        MMatch.whenIs(Type.Grey70, Function.constant('Grey70')),
        MMatch.whenIs(Type.Grey74, Function.constant('Grey74')),
        MMatch.whenIs(Type.Grey78, Function.constant('Grey78')),
      ),
      flow(
        MMatch.whenIs(Type.Grey82, Function.constant('Grey82')),
        MMatch.whenIs(Type.Grey85, Function.constant('Grey85')),
        MMatch.whenIs(Type.Grey89, Function.constant('Grey89')),
        MMatch.whenIs(Type.Grey93, Function.constant('Grey93')),
      ),
    ),
  ),
  MMatch.exhaustive,
);
