// ************** This file is automatically generated. Any modifications will be lost ************************

import {plainEslintConfig} from '@parischap/configs/LinterConfig';
export default plainEslintConfig({tsconfigRootDir:import.meta.dirname})