import * as Configs from '@parischap/configs';
import { basename, dirname } from 'path';

export default Configs.configSubRepo({
  repoName: basename(dirname(dirname(import.meta.dirname))),
  packageName: basename(import.meta.dirname),
  description: 'A functional library to replace partially the native Intl API',
  peerDependencies: { '@parischap/effect-lib': '^0.11.0', effect: '^3.18.1' },
  examples: [
    'perf.ts',
    'RoundingOption_1.ts',
    'RoundingOption_2.ts',
    'RoundingOption_3.ts',
    'NumberBase10Format_1.ts',
    'NumberBase10Format_2.ts',
    'Template_1.ts',
    'Template_2.ts',
    'Template_3.ts',
    'DateTime_1.ts',
    'DateTimeFormat_1.ts',
    'DateTimeFormat_2.ts',
    'Branding.ts',
  ],
  scripts: {},
  environment: 'Library',
  packageType: 'Library',
  isPublished: true,
  hasDocGen: true,
  keywords: [
    'number',
    'date',
    'format',
    'parse',
    'formatting',
    'parsing',
    'rounding',
    'templating',
    'conversion',
    'sscanf',
    'sprintf',
    'text',
    'n2t',
    'num2text',
    'convert',
    'typescript',
    'effect',
  ],
});
