// ************** This file is automatically generated. Any modifications will be lost ************************

export default {
  "test": {
    "fileParallelism": false,
    "include": [
      "./tests/**/*.test.ts"
    ],
    "isolate": false,
    "name": "Repo conversions",
    "pool": "threads"
  }
}