// ************** This file is automatically generated. Any modifications will be lost ************************

import {nodeEslintConfig} from '@parischap/configs/EslintConfig';
export default nodeEslintConfig({tsconfigRootDir:import.meta.dirname})