// ************** This file is automatically generated. Any modifications will be lost ************************

export default {
  test: {
    fileParallelism: false,
    include: ["./tests/**/*.test.ts"],
    isolate: false,
    name: "Repo effect-report",
    pool: "threads",
  },
};
