/* eslint-disable functional/no-expression-statements */
import { ASText } from '@parischap/ansi-styles';
import { PPOption, PPValue, PPValues } from '@parischap/pretty-print';
import { Array, flow, HashMap, pipe } from 'effect';
import { inspect } from 'node:util';
import { describe, expect, it } from 'vitest';

describe('Values', () => {
	it('fromProperties', () => {
		const topValueProto = {
			toString(): string {
				return 'MyName';
			}
		};

		const topValue1 = Object.assign(Object.create(topValueProto), {
			a: [1, 3],
			b: true
		}) as unknown;

		expect(
			pipe(
				PPValue.fromTopValue(topValue1) as PPValue.NonPrimitive,
				PPValues.fromProperties(1),
				Array.map((p) => p.toString()),
				Array.join('\n')
			)
		).toBe(`{
  "_id": "@parischap/pretty-print/Value/",
  "content": [
    1,
    3
  ],
  "contentType": 8,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "a"
  ],
  "oneLineStringKey": "a",
  "autogeneratedKey": false,
  "hasSymbolicKey": false,
  "isEnumerable": true
}
{
  "_id": "@parischap/pretty-print/Value/",
  "content": true,
  "contentType": 3,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "b"
  ],
  "oneLineStringKey": "b",
  "autogeneratedKey": false,
  "hasSymbolicKey": false,
  "isEnumerable": true
}
{
  "_id": "@parischap/pretty-print/Value/",
  "contentType": 9,
  "depth": 1,
  "protoDepth": 1,
  "stringKey": [
    "toString"
  ],
  "oneLineStringKey": "toString",
  "autogeneratedKey": false,
  "hasSymbolicKey": false,
  "isEnumerable": true
}`);
	});

	it('fromValueIterable', () => {
		expect(
			pipe(
				PPValue.fromTopValue([1, 'a']) as PPValue.NonPrimitive,
				PPValues.fromValueIterable,
				Array.map((p) => p.toString()),
				Array.join('\n')
			)
		).toBe(`{
  "_id": "@parischap/pretty-print/Value/",
  "content": 1,
  "contentType": 1,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "0"
  ],
  "oneLineStringKey": "0",
  "autogeneratedKey": true,
  "hasSymbolicKey": false,
  "isEnumerable": true
}
{
  "_id": "@parischap/pretty-print/Value/",
  "content": "a",
  "contentType": 0,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "1"
  ],
  "oneLineStringKey": "1",
  "autogeneratedKey": true,
  "hasSymbolicKey": false,
  "isEnumerable": true
}`);
	});

	it('fromKeyValueIterable', () => {
		const stringifier: PPOption.Stringifier.Type = flow(inspect, ASText.fromString, Array.of);
		expect(
			pipe(
				PPValue.fromTopValue(HashMap.make(['a', 1], ['b', 2])) as PPValue.NonPrimitive,
				PPValues.fromKeyValueIterable(stringifier),
				Array.map((p) => p.toString()),
				Array.join('\n')
			)
		).toBe(`{
  "_id": "@parischap/pretty-print/Value/",
  "content": 1,
  "contentType": 1,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "'a'"
  ],
  "oneLineStringKey": "'a'",
  "autogeneratedKey": false,
  "hasSymbolicKey": false,
  "isEnumerable": true
}
{
  "_id": "@parischap/pretty-print/Value/",
  "content": 2,
  "contentType": 1,
  "depth": 1,
  "protoDepth": 0,
  "stringKey": [
    "'b'"
  ],
  "oneLineStringKey": "'b'",
  "autogeneratedKey": false,
  "hasSymbolicKey": false,
  "isEnumerable": true
}`);
	});
});
